# Generated by Django 4.0.5 on 2022-06-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('email', models.EmailField(max_length=35, unique=True, verbose_name='email')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
    ]
