# Generated by Django 4.0.5 on 2022-06-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=35, unique=True, verbose_name='email'),
        ),
    ]
