# Generated by Django 4.0.5 on 2022-06-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(default=None, max_length=10, verbose_name='date'),
        ),
    ]
