# Generated by Django 4.0.5 on 2022-06-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_appointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=35, primary_key=True, serialize=False, unique=True, verbose_name='email'),
        ),
    ]
